import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {App,Button,Form,Input,InputNumber,Select,Tag,Tabs,Alert} from 'antd';
import {ArrowUpRight,BookOpenText,Clapperboard,Search,Plus,Layers,CheckCircle2} from 'lucide-react';
import {Link,useNavigate} from 'react-router';
import {WorkspacePage,PageHeader} from '@/components/layout/workspace-page';
import {WorkspaceLoadingState} from '@/components/layout/workspace-state';
import {AppModal} from '@/components/ui/product/app-modal';
import {getFGTopics,getFGProjects,getFGTeam,getFGStories,createFGProject,type FGTopic,type FGProject,type FGStory,type FGTeam} from '@/services/api/fg-production';
import {StoryDetails,StorySubmissions} from './stories';
import {ProductionTeam} from './team';
import {http} from '@/services/api/request';
import './production.css';
export default function FGProductionPage(){
 const [topics,setTopics]=useState<FGTopic[]>([]),[projects,setProjects]=useState<FGProject[]>([]),[team,setTeam]=useState<FGTeam|null>(null),[stories,setStories]=useState<FGStory[]>([]);
 const [error,setError]=useState(''),[loading,setLoading]=useState(true),[keyword,setKeyword]=useState(''),[tab,setTab]=useState('projects'),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<FGTopic|null>(null),[details,setDetails]=useState<FGTopic|null>(null),[saving,setSaving]=useState(false);
 const [form]=Form.useForm();const {message}=App.useApp();const navigate=useNavigate();
 const [budgetProject,setBudgetProject]=useState<FGProject|null>(null),[budget,setBudget]=useState<number|null>(0),[budgetSaving,setBudgetSaving]=useState(false);
 const requestRef=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{requestRef.current?.abort();const controller=new AbortController();requestRef.current=controller;setLoading(true);try{const [roster,t,p,s]=await Promise.all([getFGTeam(controller.signal),getFGTopics(controller.signal),getFGProjects(controller.signal),getFGStories(controller.signal)]);if(controller.signal.aborted)return;setTeam(roster);setTopics(t.topics);setProjects(p.projects);setStories(s.stories);setError('');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'读取失败');}finally{if(!controller.signal.aborted)setLoading(false);}},[]);
 useEffect(()=>{void load();return()=>requestRef.current?.abort();},[load]);
 const visible=useMemo(()=>topics.filter(t=>(filter==='all'||t.selection_group===filter)&&[t.title,t.original,t.characters,t.plot,t.selected_by,t.selection_group,t.selected_by_email].join(' ').toLowerCase().includes(keyword.toLowerCase())).sort((a,b)=>Number(!!b.selected_by)-Number(!!a.selected_by)||a.id-b.id),[topics,keyword,filter]);
 const open=(topic:FGTopic)=>{setDetails(null);setSelected(topic);form.setFieldsValue({tier:'A',budgetCny:0,groupName:team?.groups.find(g=>g.id===team.currentGroup)?.name||''});};
 const currentGroup=team?.groups.find(g=>g.id===team.currentGroup)?.name;
 return <WorkspacePage className="fg-production-page">
  <PageHeader title="故事与项目" description="经典原型 × 现代冲突 × 视觉风格。选题、分集画布与费用留在同一个项目。" actions={<Button onClick={()=>void load()} loading={loading}>刷新</Button>}/>
  <section className="fg-story-intro fg-story-studio"><div className="fg-story-studio-copy"><span className="fg-eyebrow">FG / STORY STUDIO</span><h2>好故事，从这里成为作品。</h2><p>把灵感、团队与制作连在一起。<br/>从选定一个故事，到交付下一部作品。</p><div className="fg-story-studio-actions"><Button type="primary" icon={<Plus size={16}/>} onClick={()=>setTab('topics')}>从故事开始</Button><Link to="/fg-finance">查看制作费用 <ArrowUpRight size={16}/></Link></div>{team&&<span className="fg-story-team-label">我的小组 · {currentGroup||'未分组'}</span>}</div><div className="fg-story-studio-flow" aria-label="故事制作流程"><div className="fg-story-studio-metrics"><span><strong>{loading?'—':topics.length}</strong> 个故事</span><span><strong>{loading?'—':projects.length}</strong> 个制作项目</span></div><ol>{[{icon:BookOpenText,title:'选定故事',detail:'原型、冲突与人物'},{icon:Clapperboard,title:'建立项目',detail:'小组协作与预算'},{icon:Layers,title:'分集制作',detail:'剧本、分镜与画布'},{icon:CheckCircle2,title:'完成交付',detail:'作品与费用归档'}].map((step,index)=><li key={step.title}><span className="fg-story-step-icon"><step.icon size={19}/></span><div><small>0{index+1}</small><strong>{step.title}</strong><p>{step.detail}</p></div></li>)}</ol></div></section>
  {error&&<Alert type="error" showIcon title={error} action={<Button onClick={()=>void load()}>重试</Button>}/>}
  <Tabs activeKey={tab} onChange={setTab} items={[{key:'projects',label:'制作项目 · '+projects.length},{key:'topics',label:'故事库 · '+topics.length},{key:'submissions',label:team?.canManage?'投稿与审核':'我的投稿'},{key:'team',label:'小组与成员'}]}/>
  {loading?<WorkspaceLoadingState/>:tab==='projects'?<><div className="fg-section-heading"><p>故事项目为团队共享。一部故事可创建多张分集、试片和制作画布。</p><Button icon={<Plus size={15}/>} onClick={()=>setTab('topics')}>从故事立项</Button></div><div className="fg-project-grid">
   {!projects.length?<div className="fg-story-empty"><BookOpenText size={28}/><h3>先选一个故事，建立制作项目</h3><p>把剧本、角色、分集画布和花费放在一起。</p><Button type="primary" onClick={()=>setTab('topics')}>进入故事库</Button></div>:projects.map(p=><article key={p.id} className="fg-story-card"><div className="fg-card-kicker"><Clapperboard size={16}/><span>{p.topic_id?'故事 #'+p.topic_id:'个人项目'}</span>{p.tier&&<Tag>{p.tier} 级</Tag>}{p.topic_id&&<Tag color="blue">团队共享</Tag>}</div><h3>{p.name}</h3><p className="fg-story-original">{p.topic_snapshot?.original}</p><p>{p.topic_snapshot?.conflict||p.topic_snapshot?.plot||'在项目里确定剧本、分集与视觉方向。'}</p><div className="fg-story-meta"><span>{p.group_name||'未分组'} · {p.owner_name}</span><span>{p.canvas_count} 张画布 · {Number(p.budget_cny)>0?'预算 ¥'+Number(p.budget_cny).toLocaleString('zh-CN'):'无预算上限'}</span></div><div className="fg-card-action"><Button type="primary" onClick={()=>navigate('/projects/'+p.id+'/canvases')}>打开画布 <ArrowUpRight size={15}/></Button><Link to={'/projects/'+p.id}>项目内容</Link><Link to={'/fg-finance?project='+p.id}>费用</Link>{team?.canManage&&<Button size="small" onClick={()=>{setBudgetProject(p);setBudget(Number(p.budget_cny)||0);}}>调整预算</Button>}</div></article>)}
  </div></>:tab==='topics'?<><div className="fg-story-filters"><Input prefix={<Search size={16}/>} placeholder="搜索故事、原型人物、选择人或小组" value={keyword} onChange={e=>setKeyword(e.target.value)} allowClear/><Select aria-label="原选题小组" value={filter} onChange={setFilter} options={[{value:'all',label:'全部故事'},...[...new Set(topics.map(t=>t.selection_group).filter(Boolean))].map(x=>({value:x!,label:x!}))]}/><Button onClick={()=>setTab('submissions')}>提交故事</Button></div><div className="fg-project-grid">{visible.map(t=><article className="fg-story-card" key={t.id}><div className="fg-card-kicker"><span>#{String(t.id).padStart(3,'0')}</span>{t.selected_by?<Tag color="blue">团队已选</Tag>:<Tag>{t.id>=10001?'投稿入库':'原型故事'}</Tag>}</div><h3>{t.title}</h3><p className="fg-story-original">{t.original}</p>{t.characters&&<p className="fg-story-characters">{t.characters}</p>}<p className="fg-story-clamp">{t.conflict||t.plot}</p><div className="fg-story-meta"><span>{t.form} · {t.style}</span><span>{t.markets}</span>{t.selected_by&&<span>{t.selection_group} · {t.selected_by}</span>}</div><div className="fg-card-action"><Button onClick={()=>setDetails(t)}>故事详情</Button><Button type="primary" disabled={t.blocked} onClick={()=>open(t)}>立项 <ArrowUpRight size={15}/></Button></div></article>)}</div></>:tab==='submissions'?<StorySubmissions stories={stories} canReview={!!team?.canManage} onRefresh={load}/>:team?<ProductionTeam team={team} onRefresh={load}/>:null}
  <StoryDetails story={details} onClose={()=>setDetails(null)} onProject={open}/>
  <AppModal title="从故事建立制作项目" open={!!selected} onCancel={()=>setSelected(null)} okText="建立并打开画布" confirmLoading={saving} onOk={async()=>{try{const v=await form.validateFields();setSaving(true);const result=await createFGProject({topicId:selected!.id,...v});message.success(result.reused?'已打开已有项目':'制作项目已建立');navigate('/projects/'+result.projectId+'/canvases');}catch(e){if(e instanceof Error)message.error(e.message);}finally{setSaving(false);}}}>
   <p className="fg-modal-story-title">{selected?.title}</p><Form form={form} layout="vertical"><Form.Item name="tier" label="投入档位" rules={[{required:true}]}><Select options={['S','A','B','C'].map(x=>({value:x,label:x+' 级'}))}/></Form.Item><Form.Item name="groupName" label="制作小组"><Select options={[{value:'',label:'未分组'},...(team?.groups||[]).map(g=>({value:g.name,label:g.name}))]}/></Form.Item><Form.Item name="budgetCny" label="项目预算（人民币）" extra="留空或 0 为无预算上限。建立后仅超级管理员可调整。"><InputNumber min={0} max={10000000} precision={2} style={{width:'100%'}}/></Form.Item></Form><p>同小组已有的故事项目会直接打开。进入后按分集或制作阶段创建多张画布。</p>
  </AppModal>
  <AppModal title={'调整预算 · '+budgetProject?.name} open={!!budgetProject} onCancel={()=>setBudgetProject(null)} confirmLoading={budgetSaving} onOk={async()=>{if(!budgetProject)return;setBudgetSaving(true);try{await http.patch('/fg/budgets/project',{projectId:budgetProject.id,budgetCny:budget||0});setBudgetProject(null);await load();message.success('预算已更新');}catch(e){message.error(e instanceof Error?e.message:'保存失败');}finally{setBudgetSaving(false);}}}><p>0 为不限额。已发生费用保留，后续请求按新预算检查。</p><InputNumber min={0} max={10000000} precision={2} value={budget} onChange={setBudget} className="w-full"/></AppModal>
 </WorkspacePage>;
}
