-- FG extensions live only in the sixth module database. Upstream schema stays 43.
CREATE TABLE IF NOT EXISTS fg_schema_versions(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE api_call_logs ADD COLUMN IF NOT EXISTS fg_fee_reference_id varchar(160) NOT NULL DEFAULT '';
ALTER TABLE api_call_logs ADD COLUMN IF NOT EXISTS fg_fee_references_json text NOT NULL DEFAULT '[]';
CREATE INDEX IF NOT EXISTS fg_api_fee_reference ON api_call_logs(fg_fee_reference_id) WHERE fg_fee_reference_id<>'';
CREATE TABLE IF NOT EXISTS fg_story_projects(
  id uuid PRIMARY KEY, user_id varchar(36) NOT NULL REFERENCES users(id),
  topic_id integer NOT NULL, native_project_id varchar(36) UNIQUE REFERENCES projects(id),
  topic_snapshot jsonb NOT NULL, tier varchar(1) NOT NULL CHECK(tier IN ('S','A','B','C')),
  group_name varchar(80) NOT NULL DEFAULT '', budget_cny numeric(16,2) NOT NULL CHECK(budget_cny>=0),
  created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,topic_id)
);
CREATE TABLE IF NOT EXISTS fg_fee_imports(id uuid PRIMARY KEY,actor_id varchar(36) NOT NULL REFERENCES users(id),sha256 varchar(64) NOT NULL UNIQUE,row_count integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fg_provider_fees(
  reference_id varchar(160) PRIMARY KEY, model varchar(120) NOT NULL, usd numeric(24,10) NOT NULL CHECK(usd>=0),
  fx numeric(16,6) NOT NULL CHECK(fx>0), occurred_at timestamptz NOT NULL, import_id uuid NOT NULL REFERENCES fg_fee_imports(id)
);
CREATE TABLE IF NOT EXISTS fg_model_prices(model varchar(120) PRIMARY KEY,snapshot jsonb NOT NULL,collected_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fg_company_settings(key varchar(80) PRIMARY KEY,value jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO fg_company_settings(key,value) VALUES('usdCnyRate','6.77'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO fg_schema_versions(version) VALUES(1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS fg_accounts(user_id varchar(36) PRIMARY KEY REFERENCES users(id),email varchar(254) NOT NULL,platform_role varchar(32) NOT NULL DEFAULT 'user');
CREATE TABLE IF NOT EXISTS fg_groups(id uuid PRIMARY KEY,name varchar(80) NOT NULL,archived_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS fg_group_active_name ON fg_groups(name) WHERE archived_at IS NULL;
CREATE TABLE IF NOT EXISTS fg_memberships(id uuid PRIMARY KEY,user_id varchar(36) NOT NULL REFERENCES users(id),group_id uuid NOT NULL REFERENCES fg_groups(id),role varchar(20) NOT NULL DEFAULT 'member',assigned_at timestamptz NOT NULL DEFAULT now(),unassigned_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS fg_member_current ON fg_memberships(user_id) WHERE unassigned_at IS NULL;
CREATE TABLE IF NOT EXISTS fg_stories(id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 10001) PRIMARY KEY,snapshot jsonb NOT NULL,status varchar(20) NOT NULL CHECK(status IN ('pending','approved','rejected')),submitted_by varchar(36) NOT NULL REFERENCES users(id),reviewed_by varchar(36) REFERENCES users(id),review_note varchar(1000) NOT NULL DEFAULT '',revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE api_call_logs ADD COLUMN IF NOT EXISTS fg_group_name varchar(80) NOT NULL DEFAULT '';
CREATE OR REPLACE FUNCTION fg_capture_call_group() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 NEW.fg_group_name:=COALESCE((SELECT g.name FROM fg_memberships m JOIN fg_groups g ON g.id=m.group_id WHERE m.user_id=NEW.user_id AND m.unassigned_at IS NULL AND g.archived_at IS NULL),'');
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS fg_call_group_snapshot ON api_call_logs;
CREATE TRIGGER fg_call_group_snapshot BEFORE INSERT ON api_call_logs FOR EACH ROW EXECUTE FUNCTION fg_capture_call_group();
INSERT INTO fg_schema_versions(version) VALUES(2) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS fg_resource_grants(project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,resource_id text NOT NULL REFERENCES resources(id) ON DELETE CASCADE,PRIMARY KEY(project_id,resource_id));
CREATE TABLE IF NOT EXISTS fg_asset_grants(project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,asset_id text NOT NULL REFERENCES assets(id) ON DELETE CASCADE,PRIMARY KEY(project_id,asset_id));
-- Native asset/resource IDs may have prefixes and are not limited to UUID size.
ALTER TABLE fg_resource_grants ALTER COLUMN project_id TYPE text,ALTER COLUMN resource_id TYPE text;
ALTER TABLE fg_asset_grants ALTER COLUMN project_id TYPE text,ALTER COLUMN asset_id TYPE text;
CREATE TABLE IF NOT EXISTS fg_fee_decisions(reference_id varchar(160) PRIMARY KEY REFERENCES fg_provider_fees(reference_id),call_id varchar(36) UNIQUE REFERENCES api_call_logs(id),classification varchar(24) NOT NULL CHECK(classification IN('matched','external','ignored')),note text NOT NULL,actor_id varchar(36) NOT NULL REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fg_finance_audit(id uuid PRIMARY KEY,actor_id varchar(36) NOT NULL REFERENCES users(id),action varchar(40) NOT NULL,target text NOT NULL,before_value jsonb,after_value jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fg_request_decisions(call_id varchar(36) PRIMARY KEY REFERENCES api_call_logs(id),note text NOT NULL,actor_id varchar(36) NOT NULL REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fg_user_budgets(user_id varchar(36) PRIMARY KEY REFERENCES users(id),monthly_cny numeric(16,2) NOT NULL DEFAULT 0 CHECK(monthly_cny>=0),updated_by varchar(36) REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fg_budget_reservations(id uuid PRIMARY KEY,user_id varchar(36) NOT NULL REFERENCES users(id),project_id varchar(36),task_id varchar(36),model text NOT NULL,reserved_cny numeric(20,6),created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE api_call_logs ADD COLUMN IF NOT EXISTS fg_budget_reservation_id varchar(36) NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS fg_budget_actor_time ON fg_budget_reservations(user_id,created_at);
CREATE OR REPLACE VIEW fg_fee_matches AS
 WITH automatic AS (
 SELECT f.reference_id,min(c.id) call_id FROM fg_provider_fees f JOIN api_call_logs c ON c.billable AND c.model=f.model AND c.channel_id IN(SELECT id FROM model_channels WHERE name LIKE 'WeToken%')
 AND(c.fg_fee_reference_id=f.reference_id OR c.fg_fee_references_json::jsonb ? f.reference_id OR(c.capability='video' AND c.provider_request_id=f.reference_id))
 WHERE NOT EXISTS(SELECT 1 FROM fg_fee_decisions d WHERE d.reference_id=f.reference_id)
 GROUP BY f.reference_id HAVING count(*)=1
 ), manual AS (SELECT reference_id,call_id FROM fg_fee_decisions WHERE classification='matched')
 SELECT a.reference_id,a.call_id,'automatic'::text method FROM automatic a WHERE NOT EXISTS(SELECT 1 FROM manual m WHERE m.call_id=a.call_id)
 UNION ALL SELECT reference_id,call_id,'manual'::text FROM manual;
