-- FG extensions live only in the sixth module database. Upstream schema stays 43.
CREATE TABLE IF NOT EXISTS fg_schema_versions(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE api_call_logs ADD COLUMN IF NOT EXISTS fg_fee_reference_id varchar(160) NOT NULL DEFAULT '';
ALTER TABLE api_call_logs ADD COLUMN IF NOT EXISTS fg_fee_references_json text NOT NULL DEFAULT '[]';
CREATE INDEX IF NOT EXISTS fg_api_fee_reference ON api_call_logs(fg_fee_reference_id) WHERE fg_fee_reference_id<>'';
CREATE TABLE IF NOT EXISTS fg_story_projects(
  id uuid PRIMARY KEY, user_id varchar(36) NOT NULL REFERENCES users(id),
  topic_id integer NOT NULL, native_project_id varchar(36) UNIQUE REFERENCES projects(id),
  topic_snapshot jsonb NOT NULL, tier varchar(1) NOT NULL CHECK(tier IN ('S','A','B','C')),
  group_name varchar(80) NOT NULL DEFAULT '', budget_cny numeric(16,2) NOT NULL CHECK(budget_cny>=0),
  created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,topic_id)
);
CREATE TABLE IF NOT EXISTS fg_fee_imports(id uuid PRIMARY KEY,actor_id varchar(36) NOT NULL REFERENCES users(id),sha256 varchar(64) NOT NULL UNIQUE,row_count integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fg_provider_fees(
  reference_id varchar(160) PRIMARY KEY, model varchar(120) NOT NULL, usd numeric(24,10) NOT NULL CHECK(usd>=0),
  fx numeric(16,6) NOT NULL CHECK(fx>0), occurred_at timestamptz NOT NULL, import_id uuid NOT NULL REFERENCES fg_fee_imports(id)
);
CREATE TABLE IF NOT EXISTS fg_model_prices(model varchar(120) PRIMARY KEY,snapshot jsonb NOT NULL,collected_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fg_company_settings(key varchar(80) PRIMARY KEY,value jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO fg_company_settings(key,value) VALUES('usdCnyRate','6.77'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO fg_schema_versions(version) VALUES(1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS fg_accounts(user_id varchar(36) PRIMARY KEY REFERENCES users(id),email varchar(254) NOT NULL,platform_role varchar(32) NOT NULL DEFAULT 'user');
CREATE TABLE IF NOT EXISTS fg_groups(id uuid PRIMARY KEY,name varchar(80) NOT NULL,archived_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS fg_group_active_name ON fg_groups(name) WHERE archived_at IS NULL;
CREATE TABLE IF NOT EXISTS fg_memberships(id uuid PRIMARY KEY,user_id varchar(36) NOT NULL REFERENCES users(id),group_id uuid NOT NULL REFERENCES fg_groups(id),role varchar(20) NOT NULL DEFAULT 'member',assigned_at timestamptz NOT NULL DEFAULT now(),unassigned_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS fg_member_current ON fg_memberships(user_id) WHERE unassigned_at IS NULL;
CREATE TABLE IF NOT EXISTS fg_stories(id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 10001) PRIMARY KEY,snapshot jsonb NOT NULL,status varchar(20) NOT NULL CHECK(status IN ('pending','approved','rejected')),submitted_by varchar(36) NOT NULL REFERENCES users(id),reviewed_by varchar(36) REFERENCES users(id),review_note varchar(1000) NOT NULL DEFAULT '',revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE api_call_logs ADD COLUMN IF NOT EXISTS fg_group_name varchar(80) NOT NULL DEFAULT '';
CREATE OR REPLACE FUNCTION fg_capture_call_group() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 NEW.fg_group_name:=COALESCE((SELECT g.name FROM fg_memberships m JOIN fg_groups g ON g.id=m.group_id WHERE m.user_id=NEW.user_id AND m.unassigned_at IS NULL AND g.archived_at IS NULL),'');
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS fg_call_group_snapshot ON api_call_logs;
CREATE TRIGGER fg_call_group_snapshot BEFORE INSERT ON api_call_logs FOR EACH ROW EXECUTE FUNCTION fg_capture_call_group();
INSERT INTO fg_schema_versions(version) VALUES(2) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS fg_resource_grants(project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,resource_id text NOT NULL REFERENCES resources(id) ON DELETE CASCADE,PRIMARY KEY(project_id,resource_id));
CREATE TABLE IF NOT EXISTS fg_asset_grants(project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,asset_id text NOT NULL REFERENCES assets(id) ON DELETE CASCADE,PRIMARY KEY(project_id,asset_id));
-- Native asset/resource IDs may have prefixes and are not limited to UUID size.
ALTER TABLE fg_resource_grants ALTER COLUMN project_id TYPE text,ALTER COLUMN resource_id TYPE text;
ALTER TABLE fg_asset_grants ALTER COLUMN project_id TYPE text,ALTER COLUMN asset_id TYPE text;
