import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const AGENT_NAMES = new Set(["video_agent"]);

const MODEL_ROLES = new Set(["agent"]);

export interface AgentCapability {
  readonly name: string;
  readonly operations: ReadonlyArray<string>;
  readonly model_role: string;
}

export interface AgentCapabilityContract {
  readonly contract_version: "1";
  readonly agents: ReadonlyArray<AgentCapability>;
}

export function canonicalizeAgentCapabilities(value: unknown): AgentCapabilityContract {
  if (!isRecord(value) || value.contract_version !== "1" || !Array.isArray(value.agents)) {
    invalid();
  }
  const names = new Set<string>();
  const agents = value.agents.map((rawAgent) => {
    if (
      !isRecord(rawAgent) ||
      typeof rawAgent.name !== "string" ||
      !AGENT_NAMES.has(rawAgent.name) ||
      typeof rawAgent.model_role !== "string" ||
      !MODEL_ROLES.has(rawAgent.model_role) ||
      !Array.isArray(rawAgent.operations)
    ) {
      invalid();
    }
    if (names.has(rawAgent.name)) invalid();
    names.add(rawAgent.name);

    const operations = rawAgent.operations.map((operation) => {
      if (typeof operation !== "string" || operation.trim() === "") invalid();
      return operation;
    });
    if (new Set(operations).size !== operations.length) invalid();
    return {
      name: rawAgent.name,
      operations: Object.freeze([...operations].sort()),
      model_role: rawAgent.model_role,
    };
  });
  if (agents.length !== AGENT_NAMES.size || names.size !== AGENT_NAMES.size) invalid();
  return Object.freeze({
    contract_version: "1",
    agents: Object.freeze(
      [...agents].sort((left, right) => left.name.localeCompare(right.name)),
    ),
  });
}

export async function generateAgentCapabilities(
  sourcePath: string,
  outputPath: string,
): Promise<AgentCapabilityContract> {
  const contract = canonicalizeAgentCapabilities(
    JSON.parse(await readFile(sourcePath, "utf8")),
  );
  const source = [
    "// Generated by scripts/generate-agent-capabilities.ts. Do not edit.",
    `export const AGENT_CAPABILITY_CONTRACT = ${JSON.stringify(contract, null, 2)} as const;`,
    "",
  ].join("\n");
  await writeFile(outputPath, source, "utf8");
  return contract;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function invalid(): never {
  throw new Error("agent_capability_contract_invalid");
}

async function main(): Promise<void> {
  const agentRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  await generateAgentCapabilities(
    resolve(agentRoot, "contracts/agent-capabilities.json"),
    resolve(agentRoot, "src/generated/agent-capabilities.ts"),
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  await main();
}
