import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { chromium } from "@playwright/test";
import { agentRoleAnimationRegistry } from "../src/features/agent-canvas/chat/agent-role-animation/agentRoleAnimationRegistry.ts";

// Deterministic raster export of existing approved code-native artwork; no AI redraw.
const output = new URL("../public/imgs/agent-role-icons/bitmaps-v1/", import.meta.url);
const manifest = new URL("../src/features/agent-canvas/chat/agent-role-animation/agentRoleBitmapManifest.ts", import.meta.url);
const check = process.argv.includes("--check");
const browser = await chromium.launch({ headless: true });
const entries: Record<string, { source: string; source64: string; fallback: string; revision: string }> = {};
try {
  const page = await browser.newPage();
  if (!check) await mkdir(output, { recursive: true });
  for (const [role, entry] of Object.entries(agentRoleAnimationRegistry)) {
    const Artwork = await entry.load();
    const svg = renderToStaticMarkup(React.createElement(Artwork, { motionState: "idle" }));
    const revision = createHash("sha256").update(svg).digest("hex").slice(0, 12);
    const renders = await page.evaluate(async source => {
      const image = new Image();
      image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(source)}`;
      await image.decode();
      return [32, 64, 96].map(size => {
        const canvas = document.createElement("canvas");
        canvas.width = canvas.height = size;
        canvas.getContext("2d")!.drawImage(image, 0, 0, size, size);
        return canvas.toDataURL("image/png");
      });
    }, svg);
    for (const [index, size] of [32, 64, 96].entries()) {
      const bytes = Buffer.from(renders[index]!.split(",")[1]!, "base64");
      const target = new URL(`${role}-${size}.png`, output);
      if (check) {
        if (!(await readFile(target)).equals(bytes)) throw new Error(`Stale bitmap: ${role}/${size}`);
      } else await writeFile(target, bytes);
    }
    const path = `/imgs/agent-role-icons/bitmaps-v1/${role}`;
    entries[role] = { source: `${path}-96.png?v=${revision}`, source64: `${path}-64.png?v=${revision}`, fallback: renders[0]!, revision };
  }
  const content = '// Generated by scripts/render-agent-role-bitmaps.ts; do not hand edit.\n'
    + 'import type { AgentCapabilityIdV2 } from "../../../../types-v2.ts";\n\n'
    + `export const agentRoleBitmapManifest = ${JSON.stringify(entries, null, 2)} satisfies Record<AgentCapabilityIdV2, { source: string; source64: string; fallback: string; revision: string }>;\n`;
  if (check) {
    if (await readFile(manifest, "utf8") !== content) throw new Error("Stale bitmap manifest");
  } else await writeFile(manifest, content);
  console.log(`${check ? "Verified" : "Exported"} ${Object.keys(entries).length} roles at 32/64/96px.`);
} finally {
  await browser.close();
}
