import {useCallback,useEffect,useState} from 'react';
import {App,Button,Empty,Form,Input,InputNumber,Select,Spin} from 'antd';
import {ArrowLeft,ArrowUpRight,Clapperboard,Plus,RefreshCw} from 'lucide-react';
import {Link,useSearchParams} from 'react-router';
import {WorkspacePage,PageHeader} from '@/components/layout/workspace-page';
import {AppModal} from '@/components/ui/product/app-modal';
import {http} from '@/services/api/request';
import {listAdvertisingProjects,type AdvertisingProject as Campaign,type AdvertisingProjects as WorkspaceData} from '@/services/api/fg-advertising';
import {AdvertisingWorkspace} from './advertising-workspace';
import {getFGFinance,getFGStories,type FGCall,type FGStory} from '@/services/api/fg-production';
import './advertising.css';
const money=(value:number)=>'¥'+value.toLocaleString('zh-CN',{maximumFractionDigits:2});
export default function AdvertisingPage(){
  const {message}=App.useApp();const [search,setSearch]=useSearchParams();const [data,setData]=useState<WorkspaceData>();const [calls,setCalls]=useState<FGCall[]>([]);const [stories,setStories]=useState<FGStory[]>([]);const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [form]=Form.useForm();
  const load=useCallback(async()=>{try{const [workspace,finance,storyData]=await Promise.all([listAdvertisingProjects(),getFGFinance(),getFGStories()]);setData(workspace);setCalls(finance.calls);setStories(storyData.stories.filter(s=>s.status==='approved'));setError('');}catch(e){setError(e instanceof Error?e.message:'广告项目读取失败');}},[]);
  useEffect(()=>{void load();},[load]);
  const selected=data?.workspaces.find(w=>w.id===search.get('workspace'));
  const costs=(w:Campaign)=>{const projectCalls=calls.filter(c=>c.project_id===w.native_project_id);return {settled:projectCalls.reduce((n,c)=>n+Number(c.settled_cny||0),0),pending:projectCalls.filter(c=>c.settled_cny===null).length};};
  if(selected)return <AdvertisingWorkspace key={selected.id} project={selected} onBack={()=>setSearch({})} onRefresh={load}/>;
  return <WorkspacePage className="fg-advertising-page"><PageHeader title="广告工作台" description="从产品与卖点开始，完成创意、脚本、分镜、制作与成片。" actions={<><Button icon={<RefreshCw size={15}/>} onClick={()=>void load()}>刷新</Button><Button type="primary" icon={<Plus size={16}/>} onClick={()=>{form.resetFields();setOpen(true);}}>新建广告项目</Button></>}/><section className="fg-advertising-intro"><div><span className="text-xs tracking-[0.18em] opacity-60">FG / ADVERTISING PRODUCTION</span><h2>让创意，成为下一支广告。</h2><p>每个项目保留独立工程与素材，同组成员可以接着一起制作。</p></div><Link to="/assets?library=company">公司素材库 <ArrowUpRight size={16}/></Link></section>{error?<p role="alert" className="text-sm text-red-500">{error}</p>:!data?<Spin/>:data.workspaces.length?<div className="fg-advertising-cards">{data.workspaces.map(w=>{const cost=costs(w);return <article key={w.id}><div className="fg-advertising-card-mark"><Clapperboard size={22}/><span>{w.group_name||'个人项目'}</span></div><h3>{w.name}</h3><p>{w.brief}</p><div className="fg-advertising-card-meta"><span>{w.owner_name}</span><span>预算 {money(Number(w.budget_cny))}</span></div><div className="fg-advertising-card-meta"><span>已核销 {money(cost.settled)}</span>{cost.pending>0?<span>{cost.pending} 笔待核销</span>:null}</div><Button type="primary" onClick={()=>setSearch({workspace:w.id})}>打开制作工作区 <ArrowUpRight size={15}/></Button></article>;})}</div>:<Empty description="还没有广告项目，先写下产品和制作目标。"/>}
    <AppModal title="新建广告项目" open={open} onCancel={()=>setOpen(false)} okText="创建并打开" confirmLoading={saving} onOk={async()=>{try{const v=await form.validateFields();setSaving(true);const result=await http.post<{id:string}>('/fg/advertising',v);await load();setOpen(false);setSearch({workspace:result.id});message.success('广告工程已建立');}catch(e){if(e instanceof Error)message.error(e.message);}finally{setSaving(false);}}}><Form layout="vertical" form={form} initialValues={{budgetCny:100,aspectRatio:'16:9'}}><Form.Item name="name" label="项目名称" rules={[{required:true}]}><Input maxLength={160} placeholder="例如：贝瓦儿童产品 · 秋季推广"/></Form.Item><Form.Item name="brief" label="产品与广告需求" rules={[{required:true,min:5,message:'请描述产品、卖点和制作目标'}]}><Input.TextArea rows={4} maxLength={10000} placeholder="产品、核心卖点、受众、投放平台、时长与风格…"/></Form.Item><div className="grid grid-cols-2 gap-4"><Form.Item name="groupId" label="协作小组"><Select allowClear placeholder="个人项目" options={data?.groups.map(g=>({value:g.id,label:g.name}))}/></Form.Item><Form.Item name="budgetCny" label="制作预算（人民币）" rules={[{required:true}]}><InputNumber min={0.01} max={1000000} precision={2} style={{width:'100%'}}/></Form.Item></div><div className="grid grid-cols-2 gap-4"><Form.Item name="storyId" label="关联故事（可选）"><Select allowClear showSearch optionFilterProp="label" placeholder="独立广告也可不关联" options={stories.map(s=>({value:s.id,label:s.title}))}/></Form.Item><Form.Item name="aspectRatio" label="默认画幅"><Select options={[{value:'16:9',label:'16:9 横屏'},{value:'9:16',label:'9:16 竖屏'}]}/></Form.Item></div></Form></AppModal>
  </WorkspacePage>;
}
