import type { ImageGenerationResult, ImageReference } from '@/lib/ai/image';
import {
  validateCompletedReferencePaths,
  validateStoredImageDraftRequest,
} from './image';

export const IMAGE_CONFIRM_PUBLIC_ERRORS = {
  REFERENCES_NOT_READY: '\u53c2\u8003\u56fe\u5c1a\u672a\u4e0a\u4f20\u5b8c\u6210',
  INVALID_DRAFT: '\u56fe\u7247\u4efb\u52a1\u53c2\u6570\u65e0\u6548\uff0c\u5df2\u505c\u6b62\u786e\u8ba4',
  USAGE_RECORD_FAILED: '\u56fe\u7247\u7528\u91cf\u8bb0\u5f55\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5',
  GENERATION_TIMEOUT: '\u56fe\u7247\u751f\u6210\u8d85\u65f6\uff0c\u53ef\u80fd\u5df2\u7ecf\u4ea7\u751f\u8d39\u7528\uff0c\u8bf7\u67e5\u770b\u4efb\u52a1\u72b6\u6001',
  GENERATION_FAILED: '\u56fe\u7247\u751f\u6210\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5',
  RESULT_INVALID: '\u56fe\u7247\u751f\u6210\u7ed3\u679c\u65e0\u6548\uff0c\u4efb\u52a1\u672a\u5b8c\u6210',
  RESULT_PERSIST_FAILED: '\u56fe\u7247\u7ed3\u679c\u4fdd\u5b58\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5',
  RESULT_RECONCILIATION_REQUIRED: '\u56fe\u7247\u7ed3\u679c\u5199\u5165\u72b6\u6001\u672a\u77e5\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458\u5bf9\u8d26',
  LEDGER_RECONCILIATION_REQUIRED: '\u56fe\u7247\u5df2\u751f\u6210\uff0c\u4f46\u7528\u91cf\u8d26\u672c\u5f85\u5bf9\u8d26\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458',
} as const;

export type ImageConfirmErrorCode = keyof typeof IMAGE_CONFIRM_PUBLIC_ERRORS;

/** A stable, client-safe error for the confirm route. */
export class CreatorImageConfirmError extends Error {
  readonly code: ImageConfirmErrorCode;
  readonly publicMessage: string;

  constructor(code: ImageConfirmErrorCode, cause?: unknown) {
    super(IMAGE_CONFIRM_PUBLIC_ERRORS[code], cause === undefined ? undefined : { cause });
    this.name = 'CreatorImageConfirmError';
    this.code = code;
    this.publicMessage = IMAGE_CONFIRM_PUBLIC_ERRORS[code];
  }
}

export type ConfirmImageInput = {
  taskId: string;
  userId: string;
  workspaceId: string;
};

export type ConfirmImageTask = {
  id: string;
  model: string;
  request: Record<string, unknown>;
  output?: Record<string, unknown>;
  status?: string;
  user_id?: string;
  workspace_id?: string;
};

export type ConfirmImageGenerationInput = {
  model: string;
  prompt: string;
  size: string;
  references: ImageReference[];
};

export type ConfirmImagePreflight = {
  task: ConfirmImageTask;
  input: ConfirmImageInput;
};

export type ConfirmImagePreflightResult = {
  request?: {
    effectivePrompt: string;
    size: string;
    references: Array<{ name: string; mimeType: string; size: number }>;
    referencePaths: string[];
  };
  references?: ImageReference[];
};

export type PersistImageSuccessInput = {
  task: ConfirmImageTask;
  requestId: string;
  generated: ImageGenerationResult;
};

export type SettleImageFailureInput = {
  task: ConfirmImageTask;
  requestId?: string;
  status: 'draft' | 'failed' | 'unknown';
  error: string;
};

export type ConfirmImageDependencies = {
  /** Atomic draft -> submitting claim. A null row means another confirmation won. */
  claimDraft(input: ConfirmImageInput): Promise<ConfirmImageTask | null>;
  /** Optional deep preflight. Production uses it for canonical request and Blob checks. */
  preflight?(input: ConfirmImagePreflight): Promise<ConfirmImagePreflightResult>;
  /** Read references when no custom preflight is supplied (also used by tracer tests). */
  loadReferences(paths: string[], task?: ConfirmImageTask): Promise<ImageReference[]>;
  /** Required ledger write. This is deliberately before the provider call. */
  recordAttempt(input: { requestId: string; task: ConfirmImageTask }): Promise<void>;
  /** Exactly one provider invocation after the required ledger write. */
  generate(input: ConfirmImageGenerationInput): Promise<ImageGenerationResult>;
  /** Upload/asset/task/ledger success persistence. */
  persistSuccess(input: PersistImageSuccessInput): Promise<ConfirmImageResult>;
  /** Best-effort failure state write; errors here never mask the original error. */
  settleFailure(input: SettleImageFailureInput): Promise<void>;
  /** Production validates generated bytes and MIME before uploading. */
  validateGenerated?(generated: ImageGenerationResult): void | Promise<void>;
};

export type ConfirmImageResult = {
  duplicate?: boolean;
  task?: unknown;
  asset?: unknown;
  assetId?: string;
  resultUrl?: string | null;
  ledgerStatusUpdated?: boolean;
  ledgerStatus?: 'succeeded' | 'unknown';
  requiresReconciliation?: boolean;
};

function record(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function isTimeoutError(error: unknown) {
  const name = record(error).name;
  return name === 'TimeoutError' || name === 'AbortError';
}

function publicErrorFor(error: unknown, fallback: ImageConfirmErrorCode) {
  if (error instanceof CreatorImageConfirmError) return error.publicMessage;
  return IMAGE_CONFIRM_PUBLIC_ERRORS[fallback];
}

function asCanonicalRequest(task: ConfirmImageTask, input: ConfirmImageInput) {
  const request = task.request;
  const hasCanonicalSnapshot = typeof request.effective_prompt === 'string'
    || typeof request.ratio === 'string'
    || typeof request.reference_manifest !== 'undefined';
  if (!hasCanonicalSnapshot) {
    return {
      effectivePrompt: typeof request.effective_prompt === 'string'
        ? request.effective_prompt
        : typeof request.prompt === 'string' ? request.prompt : '',
      size: typeof request.size === 'string' ? request.size : '',
      references: [],
      referencePaths: [],
    };
  }

  try {
    const validated = validateStoredImageDraftRequest(task.model, request);
    const paths = validateCompletedReferencePaths(
      request.reference_paths,
      validated.references,
      input.userId,
      input.taskId,
    );
    return {
      effectivePrompt: validated.effectivePrompt,
      size: validated.size,
      references: validated.references,
      referencePaths: paths,
    };
  } catch (error: unknown) {
    throw new CreatorImageConfirmError('INVALID_DRAFT', error);
  }
}

async function bestEffortSettle(
  deps: ConfirmImageDependencies,
  value: SettleImageFailureInput,
) {
  try {
    await deps.settleFailure(value);
  } catch {
    // A failed status write must never replace the provider/ledger error.
  }
}

/**
 * Confirm exactly one private image draft.
 *
 * All work before `recordAttempt` is free preflight. The only caller allowed
 * to reach the provider is the request that received a row from the atomic
 * draft claim.
 */
export async function confirmCreatorImage(
  input: ConfirmImageInput,
  deps: ConfirmImageDependencies,
): Promise<ConfirmImageResult> {
  const task = await deps.claimDraft(input);
  if (!task) return { duplicate: true };

  const requestId = `creator-image:${task.id}`;
  if (task.request.uploads_complete !== true) {
    const error = new CreatorImageConfirmError('REFERENCES_NOT_READY');
    await bestEffortSettle(deps, {
      task,
      status: 'draft',
      error: error.publicMessage,
    });
    throw error;
  }

  let references: ImageReference[];
  let effectivePrompt: string;
  let size: string;
  try {
    const preflight = deps.preflight
      ? await deps.preflight({ task, input })
      : undefined;
    const canonical = preflight?.request || asCanonicalRequest(task, input);
    effectivePrompt = canonical.effectivePrompt;
    size = canonical.size;
    references = preflight?.references
      || await deps.loadReferences(canonical.referencePaths, task);
    if (!effectivePrompt.trim() || !size) {
      throw new CreatorImageConfirmError('INVALID_DRAFT');
    }
  } catch (error: unknown) {
    const normalized = error instanceof CreatorImageConfirmError
      ? error
      : new CreatorImageConfirmError('INVALID_DRAFT', error);
    await bestEffortSettle(deps, {
      task,
      status: 'draft',
      error: normalized.publicMessage,
    });
    throw normalized;
  }

  try {
    await deps.recordAttempt({ requestId, task });
  } catch (error: unknown) {
    const normalized = new CreatorImageConfirmError('USAGE_RECORD_FAILED', error);
    await bestEffortSettle(deps, {
      task,
      requestId,
      status: 'draft',
      error: normalized.publicMessage,
    });
    throw normalized;
  }

  try {
    const generated = await deps.generate({
      model: task.model,
      prompt: effectivePrompt,
      size,
      references,
    });
    await deps.validateGenerated?.(generated);
    return await deps.persistSuccess({ task, requestId, generated });
  } catch (error: unknown) {
    if (error instanceof CreatorImageConfirmError && error.code === 'RESULT_RECONCILIATION_REQUIRED') {
      throw error;
    }
    const timeout = isTimeoutError(error);
    const status = timeout ? 'unknown' : 'failed';
    const code: ImageConfirmErrorCode = timeout ? 'GENERATION_TIMEOUT' : 'GENERATION_FAILED';
    await bestEffortSettle(deps, {
      task,
      requestId,
      status,
      error: publicErrorFor(error, code),
    });
    throw error;
  }
}
