import {useEffect,useState} from 'react';
import {fgWorkspace} from './fg-scope';
import './styles/fg-workspace-bar.css';
type Workspace={id:string;name:string;budget_cny:string;native_project_id:string;can_manage:boolean;can_budget:boolean};
async function api(path:string,method='GET',body?:unknown){const r=await fetch('/api/fg/'+path,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok||d.code!==0)throw Error(d.msg||'操作失败');return d.data;}
export function FGWorkspaceBar(){
 const [workspace,setWorkspace]=useState<Workspace>(),[error,setError]=useState(''),[panel,setPanel]=useState(''),[budget,setBudget]=useState('0'),[busy,setBusy]=useState(false);
 const [users,setUsers]=useState<Array<{id:string;name:string}>>([]),[members,setMembers]=useState<string[]>([]),[assets,setAssets]=useState<Array<{id:string;title:string}>>([]),[asset,setAsset]=useState('');
 const load=()=>api('advertising').then(d=>setWorkspace(d.workspaces.find((w:Workspace)=>w.id===fgWorkspace))).catch(e=>setError(e.message));
 useEffect(()=>{if(fgWorkspace)void load();const guide=()=>setPanel('guide');window.addEventListener('fg-ad-guide',guide);return()=>window.removeEventListener('fg-ad-guide',guide);},[]);
 if(!fgWorkspace)return null;
 async function show(which:string){setError('');try{if(which==='share'){const d=await api('advertising/'+fgWorkspace+'/members');setUsers(d.users);setMembers(d.members);}if(which==='assets'){const r=await fetch('/api/fg-company-assets?pageSize=100');const d=await r.json();if(d.code!==0)throw Error(d.msg);setAssets(d.data.assets);}if(which==='budget')setBudget(workspace?.budget_cny||'0');setPanel(which);}catch(e){setError(e instanceof Error?e.message:'读取失败');}}
 async function save(){setBusy(true);try{if(panel==='budget'){const n=Number(budget);if(!Number.isFinite(n)||n<0)throw Error('请输入有效预算');await api('advertising/'+fgWorkspace+'/budget','PATCH',{budgetCny:n});await load();}else if(panel==='share')await api('advertising/'+fgWorkspace+'/members','PUT',{userIds:members});else if(panel==='assets'){if(!asset)throw Error('请选择素材');await api('advertising/'+fgWorkspace+'/company-asset','POST',{assetId:asset});}setPanel('');}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 return <><div className="fg-ad-bar"><a href="/advertising">← 广告项目</a><strong>{workspace?.name||'FG 广告工作台'}</strong><span>{Number(workspace?.budget_cny)>0?'预算 ¥'+workspace?.budget_cny:'无预算上限'}</span><div className="fg-ad-bar-actions"><button onClick={()=>void show('assets')}>公司素材</button>{workspace?.can_manage&&<button onClick={()=>void show('share')}>邀请协作</button>}{workspace?.can_budget&&<button onClick={()=>void show('budget')}>调整预算</button>}<a href={'/fg-finance?project='+workspace?.native_project_id}>人民币费用 ↗</a></div></div>{error&&!panel&&<p className="fg-ad-error" role="alert">{error}</p>}
 {panel&&<div className="fg-ad-modal-backdrop"><section className="fg-ad-modal" role="dialog" aria-modal="true" aria-label={panel==='guide'?'广告工作台使用指南':panel==='share'?'邀请协作':panel==='assets'?'公司素材':'项目预算'}><h2>{panel==='guide'?'广告工作台使用指南':panel==='share'?'邀请同事协作':panel==='assets'?'导入公司素材':'调整项目预算'}</h2>{panel==='guide'?<ol className="fg-ad-guide"><li>从 FG 广告项目页创建工程，写明产品、受众、卖点与目标时长。</li><li>在画布顶部“＋”添加文本、脚本、图片或视频节点；把产品参考素材上传到节点，也可以导入公司素材。</li><li>在右侧广告助手描述需求，选择文本模型；助手可以拆解创意、编写脚本并安排制作。启用自动制作前先核对需求与预算。</li><li>打开节点的制作面板，选择模型与参数，查看人民币价格，再确认生成。参考节点可以连线传入下一步。</li><li>结果与工程自动保存到服务器和 NAS；从广告项目页再次打开即可继续。下载和剪辑入口用于导出成品。</li><li>预算 0 为不限额；有预算时超额请求会被拦截，只有超级管理员可以调整。费用页按实际账单核销。</li><li>项目默认私有，需要协作时邀请同事；同一画布由一人编辑，进入后可接管编辑权。</li></ol>:panel==='budget'?<><p>人民币预算。0 为不限额，仅超级管理员可调整。</p><input aria-label="人民币预算" type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)}/></>:panel==='share'?<><p>广告项目默认私有，仅选中的同事可以共同编辑。</p><div className="fg-ad-members">{users.map(u=><label key={u.id}><input type="checkbox" checked={members.includes(u.id)} onChange={e=>setMembers(m=>e.target.checked?[...m,u.id]:m.filter(id=>id!==u.id))}/>{u.name}</label>)}</div></>:<select aria-label="公司素材" value={asset} onChange={e=>setAsset(e.target.value)}><option value="">选择素材</option>{assets.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select>}{error&&<p role="alert" className="fg-ad-error">{error}</p>}<footer><button disabled={busy} onClick={()=>{setPanel('');setError('');}}>{panel==='guide'?'知道了':'取消'}</button>{panel!=='guide'&&<button disabled={busy} onClick={()=>void save()}>{busy?'保存中…':panel==='assets'?'导入':'保存'}</button>}</footer></section></div>}</>;
}
