import {useEffect,useState} from 'react';
import {fgWorkspace} from './fg-scope';
import './styles/fg-workspace-bar.css';
type Workspace={id:string;name:string;budget_cny:string;native_project_id:string;can_manage:boolean;can_budget:boolean};
async function api(path:string,method='GET',body?:unknown){const r=await fetch('/api/fg/'+path,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok||d.code!==0)throw Error(d.msg||'操作失败');return d.data;}
export function FGWorkspaceBar(){
 const [workspace,setWorkspace]=useState<Workspace>(),[error,setError]=useState(''),[panel,setPanel]=useState(''),[budget,setBudget]=useState('0'),[busy,setBusy]=useState(false);
 const [users,setUsers]=useState<Array<{id:string;name:string}>>([]),[members,setMembers]=useState<string[]>([]),[assets,setAssets]=useState<Array<{id:string;title:string}>>([]),[asset,setAsset]=useState('');
 const load=()=>api('advertising').then(d=>setWorkspace(d.workspaces.find((w:Workspace)=>w.id===fgWorkspace))).catch(e=>setError(e.message));
 useEffect(()=>{if(fgWorkspace)void load();},[]);
 if(!fgWorkspace)return null;
 async function show(which:string){setError('');try{if(which==='share'){const d=await api('advertising/'+fgWorkspace+'/members');setUsers(d.users);setMembers(d.members);}if(which==='assets'){const r=await fetch('/api/fg-company-assets?pageSize=100');const d=await r.json();if(d.code!==0)throw Error(d.msg);setAssets(d.data.assets);}if(which==='budget')setBudget(workspace?.budget_cny||'0');setPanel(which);}catch(e){setError(e instanceof Error?e.message:'读取失败');}}
 async function save(){setBusy(true);try{if(panel==='budget'){const n=Number(budget);if(!Number.isFinite(n)||n<0)throw Error('请输入有效预算');await api('advertising/'+fgWorkspace+'/budget','PATCH',{budgetCny:n});await load();}else if(panel==='share')await api('advertising/'+fgWorkspace+'/members','PUT',{userIds:members});else if(panel==='assets'){if(!asset)throw Error('请选择素材');await api('advertising/'+fgWorkspace+'/company-asset','POST',{assetId:asset});}setPanel('');}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 return <><div className="fg-ad-bar"><a href="/advertising">← 广告项目</a><strong>{workspace?.name||'FG 广告工作台'}</strong><span>{Number(workspace?.budget_cny)>0?'预算 ¥'+workspace?.budget_cny:'无预算上限'}</span><div className="fg-ad-bar-actions"><button onClick={()=>void show('assets')}>公司素材</button>{workspace?.can_manage&&<button onClick={()=>void show('share')}>邀请协作</button>}{workspace?.can_budget&&<button onClick={()=>void show('budget')}>调整预算</button>}<a href={'/fg-finance?project='+workspace?.native_project_id}>人民币费用 ↗</a></div></div>{error&&!panel&&<p className="fg-ad-error" role="alert">{error}</p>}
 {panel&&<div className="fg-ad-modal-backdrop"><section className="fg-ad-modal" role="dialog" aria-modal="true" aria-label={panel==='share'?'邀请协作':panel==='assets'?'公司素材':'项目预算'}><h2>{panel==='share'?'邀请同事协作':panel==='assets'?'导入公司素材':'调整项目预算'}</h2>{panel==='budget'?<><p>人民币预算。0 为不限额，仅超级管理员可调整。</p><input aria-label="人民币预算" type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)}/></>:panel==='share'?<><p>广告项目默认私有，仅选中的同事可以共同编辑。</p><div className="fg-ad-members">{users.map(u=><label key={u.id}><input type="checkbox" checked={members.includes(u.id)} onChange={e=>setMembers(m=>e.target.checked?[...m,u.id]:m.filter(id=>id!==u.id))}/>{u.name}</label>)}</div></>:<select aria-label="公司素材" value={asset} onChange={e=>setAsset(e.target.value)}><option value="">选择素材</option>{assets.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select>}{error&&<p role="alert" className="fg-ad-error">{error}</p>}<footer><button disabled={busy} onClick={()=>{setPanel('');setError('');}}>取消</button><button disabled={busy} onClick={()=>void save()}>{busy?'保存中…':panel==='assets'?'导入':'保存'}</button></footer></section></div>}</>;
}
