export function buildCodexProbeArgs(input: {
  cwd: string;
  outputPath: string;
}): string[] {
  return [
    'exec',
    '--json',
    '--ephemeral',
    '--skip-git-repo-check',
    '--ignore-rules',
    '--sandbox',
    'read-only',
    '-c',
    'approval_policy="never"',
    '-c',
    'model_reasoning_effort="low"',
    '-c',
    'model_verbosity="low"',
    '-c',
    'mcp_servers={}',
    '-c',
    'plugins={}',
    '-c',
    'web_search="disabled"',
    '-c',
    'notify=[]',
    '-c',
    'check_for_update_on_startup=false',
    '--disable',
    'hooks',
    '--disable',
    'plugins',
    '--disable',
    'apps',
    '--disable',
    'multi_agent',
    '--disable',
    'browser_use',
    '--disable',
    'computer_use',
    '--disable',
    'in_app_browser',
    '--disable',
    'image_generation',
    '--disable',
    'tool_suggest',
    '--disable',
    'shell_tool',
    '--disable',
    'unified_exec',
    '--disable',
    'shell_snapshot',
    '-C',
    input.cwd,
    '--output-last-message',
    input.outputPath
  ];
}
